### ISSUE TITLE
Investigate `browser_check` failure

### ISSUE THREAD

**Issue by trungleduc** [QuantStack/jupyter-suggestions#14]
The `browser_check` test of JupyterLab has failed because of this error https://github.com/QuantStack/jupyter-suggestions/actions/runs/12285648889/job/34284127425#step:7:395

I cannot reproduce it on my machine, a quick Google search led to these variables.

_Originally posted by @trungleduc in https://github.com/QuantStack/jupyter-suggestions/pull/12#discussion_r1884303207_

**Comment by jtpio** [comment]
Another report about the failing browser check: https://github.com/jupyterlab/jupyterlab/issues/17079

**Comment by brichet** [comment]
FYI it should be fixed now, after release of lab 4.3.4, including https://github.com/jupyterlab/jupyterlab/pull/17094
