### ISSUE TITLE
Rename `@jupyter/jupyter-suggestions-base` to `@jupyter/suggestions-base`?

### ISSUE THREAD

**Issue by jtpio** [QuantStack/jupyter-suggestions#9]
To prepare for an eventual first release, a question about the name of this package:

https://github.com/QuantStack/jupyterlab-suggestions/blob/26b00123d50a846cf200c9c49488bd1c2279a79d/python/jupyter_suggestions_core/package.json#L2

Currently it's set to `@jupyter/jupyter-suggestions-base`, but maybe it could make sense to stick to a shorter `@jupyter/suggestions-base` for consistency?

**Comment by trungleduc** [comment]
yes, it looks a lot better!

**Comment by trungleduc** [comment]
maybe also rename the repo to `jupyter-suggestions`

**Comment by jtpio** [comment]
> maybe also rename the repo to `jupyter-suggestions`

Done: https://github.com/QuantStack/jupyter-suggestions

**Comment by trungleduc** [comment]
Fixed by #12
